### ISSUE TITLE
Gemfile.lock issues

### ISSUE THREAD

**Issue by mkarliner** [tomjohnson1492/documentation-theme-jekyll#28]
bundle install did not install all gems.

 on jekyll serve I got this error

WARN: Unresolved specs during Gem::Specification.reset:
      jekyll-watch (~> 1.1)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
Configuration file: /Users/mike/Src/ThingStudio/documentation-theme-jekyll/_config.yml
  Dependency Error: Yikes! It looks like you don't have kramdown or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. The full error message from Ruby is: 'cannot load such file -- kramdown' If you run into trouble, you can find helpful resources at http://jekyllrb.com/help/!

I had to remove Gemfile.lock  and re-run bundle install to get it to work.

**Comment by erinkcochran87** [comment]
For anyone else who runs into a similar error, it may also related to [this](https://github.com/bundler/bundler/issues/5154) (original issue) and  [this](https://github.com/github/pages-gem/issues/351).

If you're using Github pages, update the gem and then find older versions of dependent gems being installed, it's probably due to the bug with bundler mentioned in those issues. I solved this yesterday by doing this hacky workaround in my Gemfile and then re-running `bundle install`:

```
source "https://rubygems.org"

gem 'github-pages', '105'     // specifying a version fixes this issue (for now)
gem 'jekyll'
```

**Comment by tomjoht** [comment]
Thanks for the feedback. I'm not sure if this helped, but I just deleted Gemfile.lock, re-ran Bundle install (which creates a new Gemfile.lock), and updated the theme. Hopefully this might help avoid any outdated gems.

**Comment by erinkcochran87** [comment]
That's the first thing I did yesterday - I wish it would have worked for me! Glad it was an easy fix for you, though. Thanks, Tom.
