### ISSUE TITLE
Automated Links not behaving as described

### ISSUE THREAD

**Issue by matthew-dews** [tomjohnson1492/documentation-theme-jekyll#30]
I believe that the description of how Automated Links works is incorrect.
From the [links page](http://idratherbewriting.com/documentation-theme-jekyll/mydoc_hyperlinks.html#automatedlinks):

> 1. To link to a topic, use reference-style Markdown links, with the referent using the **file name** (without the file extension). 

However the code in _includes/links.html indicates that these links are based on the url field of the page. The url field is derived from the filename and path of the source file but most of the example documentation pages have a permalink specified which overrides [the default style](https://jekyllrb.com/docs/permalinks/#built-in-permalink-styles). Most permalinks are all the same as the filename, with the addition of the .html extension and / character.

Renaming a markdown file does not break automated links like we would expect it to if the filename if automated links were based on file names. Only changing or removing permalinks will break them.

**Comment by tomjoht** [comment]
Good point. The links.html approach requires the permalink to match the file name. The sidebar data file (for example, mydoc_sidebar.yml) manually sets the "url" for each item:

```
    - title: About the theme author
      url: /mydoc_about.html
      output: web, pdf
```

Then the links.html file sets the url based on how the sidebar listed it:

```
{% for folderitem in folder.folderitems %}
[{{folderitem.url | remove: "/"  | remove: ".html"}}]: {{folderitem.url | remove: "/"}}
{% endif %}
```

But whether that URL will work or not depends on whether the page has a permalink set to that URL. If there isn't a permalink set to the URL, then nothing will appear when someone goes to that link (because the page won't be in the root -- it will be in a subdirectory in the output). I added a note in the links doc that reinforces the permalink requirement. I wrote:

<blockquote>
For the automated links method to work, each of your pages must have a permalink property in the frontmatter. The permalink property must match the file name. For example, if the file name is somefile.html, your permalink property would be somefile.html. See Pages for more details.</blockquote>

BTW, what do you think of this approach for automating links?

**Comment by matthew-dews** [comment]
I think the way of automating links works is fine. I think Jekyll makes links tricky, or I at least haven't found a way to do them that satisfies me. My preference is to have the links based on the name and path of the Markdown file, which is what Jekyll does by default in generating each page's URL.

When I was playing around with version 6 I made this change to links.html, which removes the edge case of pages that you don't want to include in your sidebar or navbar, but want to link to. 

```
{% for page in site.pages %}
{% if page.url != "/" %}
[{{page.url | remove: "/"  | remove: ".html"}}]: {{page.url | remove: "/"}}
{% endif %}
{% endfor %}
```
