### ISSUE TITLE
Company logo on the top navigation bar

### ISSUE THREAD

**Issue by abirger** [tomjohnson1492/documentation-theme-jekyll#89]
Is it possible to move a logo from the footer to the left side of the top navigation bar? I need to do that to keep the documentation pages in the same style as the organization's main site. Thanks.

**Comment by ghost** [comment]
You'd just need to remove the image from footer.html and add an image where you want it, in one of the other include files.

Since you're trying to match a specific style, I'd suggest this is something you should change in your local copy of the template to be exactly how you want it, and not something that should be changed in this repo.
